#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 13 19:25:34 2024
@author: Tz Wang <wangtianze23@mails.ucas.ac.cn>
"""

from model.evaluation.FunctionalFactory import BuiltinFunctionalFactory
from model.optimization.Constraint import RegulationConstraint,TargetConstraint
from model.optimization.Network import Node, OptimizedRegulation
from model.optimization.NetworkOptimizer import AcyclicNetworkOptimizer
from model.optimization.OptimizerException import \
    NetworkTypeNotSupportedException, TargetTypeNotSupportedException
from model.simulation.Network import AcyclicNetwork
from model.simulation.NetworkFactory import BaseNetworkFactory,PairedRegulation


class OptimizationResult:
    """
    The container class for the result of network optimization.
    """
    def __init__(self, regulations: list[OptimizedRegulation], 
                 targets: list[float], message = ''):
        """
        Initialize an OptimizationResult object.

        Parameters
        ----------
        regulations : list
            A list of OptimizedRegulation objects containing the optimized 
            regulations in a network.
        targets : list
            A list of float containing the optimized target values.
        message : str, optional
            A string representing the message generated by the optimizer.
            The default is an empty string.

        Returns
        -------
        None.
        """
        self.regulations = regulations
        self.targets = targets
        self.message = message

class NetworkOptimizer:
    """
    The class for optimizing transcription networks.
    """
    def __init__(self):
        """
        Initialize a NetworkOptimizer object.
        
        Returns
        -------
        None.
        """
        self.debugOutput = False
        self.maxIteration = 100
        self.seed = None
        self.trajectoryCount = 1000
    
    def setDebugOutput(self, debugOutput = True):
        """
        Set the output of debug information.

        Parameters
        ----------
        debugOutput :bool, optional
            Whether to print detailed information about the optimization to 
            the standard output.
            The default is True.

        Returns
        -------
        None.
        """
        self.debugOutput = debugOutput
    
    def setMaximumIteration(self, maxIteration = 100):
        """
        Set the number of iteration for optimization.

        Parameters
        ----------
        maxIteration : int, optional
            An integer indicating the maximum number of iteration. 
            The default is 100.

        Returns
        -------
        None.
        """
        self.maxIteration = maxIteration
    
    def setSeed(self, seed = None):
        """
        Set the seed for the random number generator (RNG) when generating 
        sequences.

        Parameters
        ----------
        seed : int or NoneType
            An integer fed to the RNG, or None if no fixed seed is used.
            The default is None.

        Returns
        -------
        None.
        """
        self.seed = seed
    
    def setTrajectoryCount(self, trajectoryCount = 1000):
        """
        Set the number of trajectories for simulation of system dynamics.

        Parameters
        ----------
        count : int, optional
            An integer indicating the number of trajectories.
            The default is 1000.

        Returns
        -------
        None.
        """
        self.trajectoryCount = trajectoryCount
    
    def optimizeWithSpaceAndTarget(self, 
                                   nodeList: list[Node], 
                                   edgeList: list[RegulationConstraint], 
                                   targetList: list[TargetConstraint])\
                                  -> OptimizationResult:
        """
        Optimize a network with given topology and targets.

        Parameters
        ----------
        nodeList : list
            A list of Node objects indicating all entities in the network.
        edgeList : list
            A list of RegulationConstraint object indicating the regulations 
            among entities and the corresponding constraints on their 
            parameters during optimization.
        targetList : list
            A list of TargetConstraint objects indicating the target functions 
            to optimize.
        
        Raises
        ------
        NetworkTypeNotSupportedException
            Raised when the network of specified topology is not supported.
        TargetTypeNotSupportedException
            Raised when the type of a specified target is not supported.

        Returns
        -------
        OptimizationResult
            An OptimizationResult object containing the result of optimization.
        """
        # Create a network of specified topologies
        nodeCount = len(nodeList)
        regulations = [PairedRegulation(edge.sourceIndex, edge.targetIndex, 
                                        1 if edge.regulationType=='activation' 
                                        else -1, 
                                        [min(X) if X is not None else 0 
                                         for X in 
                                         edge.parameterSpace.boundaries])
                       for edge in edgeList]
        network, parameterMapping = \
            BaseNetworkFactory.createFromPairedRegulations(nodeCount, 
                                                           regulations)
        if not isinstance(network, AcyclicNetwork):
            raise NetworkTypeNotSupportedException('cyclic')
        
        # Check the validity of all targets
        invalidTargets = [X for X in targetList 
                          if len(X.nodeIndexes) != 2 or 
                             len(X.space.builtin) == '' or 
                             X.space.variableCount != 2]
        if len(invalidTargets) > 0:
            raise TargetTypeNotSupportedException(
                                ','.join(X.space.name for X in invalidTargets))
        
        # Create wrapped target functions to optimize
        paths = [network.getPath(X.nodeIndexes[1], X.nodeIndexes[0]) 
                 for X in targetList]
        pathFunctions = [lambda X, F = Y: F(X[0]) for Y in paths]
        targetFunctionals = [BuiltinFunctionalFactory.
                             createFromBuiltinName(X.space.builtin, 
                                                   X.valueRanges)
                             for X in targetList]
        targetFunctions = [lambda T = X, F = Y: T(F) 
                           for X, Y in zip(targetFunctionals, pathFunctions)]
        
        # Optimize the network
        optimizer = AcyclicNetworkOptimizer()
        optimizer.setDebugOutput(self.debugOutput)
        optimizer.setMaximumIteration(self.maxIteration)
        optimizer.setSeed(self.seed)
        optimizedRegulations = optimizer.optimize(network, edgeList, 
                                                  parameterMapping, 
                                                  targetFunctions)
        
        # Re-evaluate the optimized target functions
        optimizedTargets = [X(Y) 
                            for X, Y in zip(targetFunctionals, pathFunctions)]
        
        return OptimizationResult(optimizedRegulations, optimizedTargets)
