#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Sep 13 19:25:34 2024
@author: Tz Wang <wangtianze23@mails.ucas.ac.cn>
"""

from model.evaluation.FunctionalFactory import BuiltinFunctionalFactory
from model.optimization.Constraint import RegulationConstraint,TargetConstraint
from model.optimization.Network import Node, OptimizedRegulation
from model.optimization.ParameterOptimizer import BaseNetworkParameterOptimizer
from model.optimization.OptimizerException import \
    TargetTypeNotSupportedException
from model.simulation.DynamicNetwork import BaseDynamicNetwork
from model.simulation.Network import AcyclicNetwork
from model.simulation.NetworkFactory import BaseNetworkFactory,PairedRegulation


class DynamicSimulationOption:
    """
    The container class of options for simulation of system dynamics.
    """
    def __init__(self, minNoise = 0.001, relativeNoise = 0.2, 
                 timeSpan = 24, trajectoryCount = 1000):
        """
        Initalize a DynamicSimulationOptions object.

        Parameters
        ----------
        minNoise : int or float, optional
            A numeric value indicating the minimum absolute noise level.
            The default is 0.001.
        relativeNoise : int or float, optional
            A numeric value indicating the relative noise level.
            The default is 0.2, i.e. a gaussian noise with mean = 0 and 
            standard deviation = 0.2 * (current value of regulated variable).
        timeSpan : int or float, optional
            A numeric value indicating the span of time for simulation.
            The default is 24.
        count : int, optional
            An integer indicating the number of trajectories.
            The default is 1000.

        Returns
        -------
        None.
        """
        self.minNoise = abs(minNoise)
        self.relativeNoise = abs(relativeNoise)
        self.timeSpan = max(timeSpan, 0)
        self.trajectoryCount = max(trajectoryCount, 0)

class OptimizationResult:
    """
    The container class for the result of network optimization.
    """
    def __init__(self, regulations: list[OptimizedRegulation], 
                 targets: list[float], message = ''):
        """
        Initialize an OptimizationResult object.

        Parameters
        ----------
        regulations : list
            A list of OptimizedRegulation objects containing the optimized 
            regulations in a network.
        targets : list
            A list of float containing the optimized target values.
        message : str, optional
            A string representing the message generated by the optimizer.
            The default is an empty string.

        Returns
        -------
        None.
        """
        self.regulations = regulations
        self.targets = targets
        self.message = message

class NetworkOptimizer:
    """
    The class for optimizing transcription networks.
    """
    def __init__(self):
        """
        Initialize a NetworkOptimizer object.
        
        Returns
        -------
        None.
        """
        self.debugOutput = False
        self.maxIteration = 100
        self.seed = None
        self.simulationOption = DynamicSimulationOption()
    
    def setDebugOutput(self, debugOutput = True):
        """
        Set the output of debug information.

        Parameters
        ----------
        debugOutput :bool, optional
            Whether to print detailed information about the optimization to 
            the standard output.
            The default is True.

        Returns
        -------
        None.
        """
        self.debugOutput = debugOutput
    
    def setMaximumIteration(self, maxIteration = 100):
        """
        Set the number of iteration for optimization.

        Parameters
        ----------
        maxIteration : int, optional
            An integer indicating the maximum number of iteration. 
            The default is 100.

        Returns
        -------
        None.
        """
        self.maxIteration = maxIteration
    
    def setSeed(self, seed = None):
        """
        Set the seed for the random number generator (RNG) when generating 
        sequences.

        Parameters
        ----------
        seed : int or NoneType
            An integer fed to the RNG, or None if no fixed seed is used.
            The default is None.

        Returns
        -------
        None.
        """
        self.seed = seed
    
    def setSimulationOption(self, option: DynamicSimulationOption):
        """
        Set the noise level for simulation of system dynamics.

        Parameters
        ----------
        option : DynamicSimulationOption
            A DynamicSimulationOption object containing the parameters 
            used for simulating the networks during optimization.

        Returns
        -------
        None.
        """
        self.simulationOption = option
    
    def optimizeWithSpaceAndTarget(self, 
                                   nodeList: list[Node], 
                                   edgeList: list[RegulationConstraint], 
                                   targetList: list[TargetConstraint])\
                                  -> OptimizationResult:
        """
        Optimize a network with given topology and targets.

        Parameters
        ----------
        nodeList : list
            A list of Node objects indicating all entities in the network.
        edgeList : list
            A list of RegulationConstraint object indicating the regulations 
            among entities and the corresponding constraints on their 
            parameters during optimization.
        targetList : list
            A list of TargetConstraint objects indicating the target functions 
            to optimize.
        
        Raises
        ------
        NetworkTypeNotSupportedException
            Raised when the network of specified topology is not supported.
        TargetTypeNotSupportedException
            Raised when the type of a specified target is not supported.

        Returns
        -------
        OptimizationResult
            An OptimizationResult object containing the result of optimization.
        """
        # Create a network of specified topologies
        nodeCount = len(nodeList)
        regulations = [PairedRegulation(edge.sourceIndex, edge.targetIndex, 
                                        1 if edge.regulationType=='activation' 
                                        else 
                                        -1 if edge.regulationType=='repression'
                                        else 0, 
                                        [min(X) if X is not None else 0 
                                         for X in 
                                         edge.parameterSpace.boundaries])
                       for edge in edgeList]
        network, parameterMapping = \
            BaseNetworkFactory.createFromPairedRegulations(nodeCount, 
                                                           regulations)
        acyclic = isinstance(network, AcyclicNetwork)
        if not acyclic:
            network = BaseDynamicNetwork.fromBaseNetwork(
                                          network, 
                                          self.simulationOption.minNoise, 
                                          self.simulationOption.relativeNoise)
            network.setSeed(self.seed)
        
        # Check the validity of all targets
        invalidTargets = [X for X in targetList 
                          if len(X.space.builtin) == '' or 
                             X.space.variableCount > 0 and 
                             X.space.variableCount != len(X.nodeIndexes)]
        if len(invalidTargets) > 0:
            raise TargetTypeNotSupportedException(
                                ','.join(X.space.name for X in invalidTargets))
        
        # Create wrapped target functions to optimize
        targetFunctionals = [BuiltinFunctionalFactory.
                             createFromBuiltinName(X.space.builtin, 
                                                   X.valueRanges)
                             for X in targetList]
        expectedValues = [X.expectedValue for X in targetList]
        if acyclic:
            paths = [network.getPath(X.nodeIndexes[1], X.nodeIndexes[0]) 
                     for X in targetList]
            inputFunctions = [lambda X, F = Y: F(X[0]) for Y in paths]
        else:
            initialVariables = [0] * nodeCount
            inputFunctions = [lambda: 
                              [Y[X.nodeIndexes[0]] 
                               for Y in network.evolve(
                                        initialVariables, 
                                        self.simulationOption.timeSpan, 
                                        self.simulationOption.trajectoryCount)]
                              for X in targetList]
        targetFunctions = [(lambda T = X, F = Y: T(F)) if Z is None 
                           else (lambda T = X, F = Y, E = Z: (T(F) - E) ** 2) 
                           for X, Y, Z in zip(targetFunctionals, 
                                              inputFunctions, expectedValues)]
        
        # Optimize the network
        optimizer = BaseNetworkParameterOptimizer()
        optimizer.setDebugOutput(self.debugOutput)
        optimizer.setMaximumIteration(self.maxIteration)
        optimizer.setSeed(self.seed)
        optimizedRegulations = optimizer.optimize(network, edgeList, 
                                                  parameterMapping, 
                                                  targetFunctions)
        
        # Re-evaluate the optimized target functions
        optimizedTargets = [X() for X in targetFunctions]
        
        return OptimizationResult(optimizedRegulations, optimizedTargets)
